= Rewrite frontend from Next.js to another framework

== Context

While working with Next.js, I've made a decision based on popularity and my previous experience with it. However, I've realized that it's not the best choice.

After reading some posts on Reddit and blog posts, I've become aware of the limitations of Next.js.

=== Limitations of Next.js

In perspective of my project, I've found some limitations of Next.js:

- upgrade to Next.js 15.2 from 15.1, marked as minor, brought some breaking changes in tailwindcss, which was already causing me a pain,
- several link:https://www.reddit.com/r/reactjs/comments/1fogphw/next_js_why_or_why_not/[posts on reddit] points out, that Next.js is having an issues with maintaining backward compatibility between versions,
- there's a lot of controversy around Next.js, as major stakeholder is also a hosting provider, which may lead to some conflicts of interest.

== Decision

I've decided to rewrite the frontend from Next.js to another framework.

== Next steps

I will evaluate other frameworks and choose the one that fits my needs the best.

I'll look into the following frameworks:

- vite